# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PickM' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'SwiftyJSON', git: 'https://github.com/BaiduHiDeviOS/SwiftyJSON.git', branch: 'swift3’

end
